---

- hosts: hanas

  vars:
  
    sap_hana_hsr_hana_sid: "RHE"
    sap_hana_hsr_hana_instance_number: "01"
    sap_hana_hsr_hana_db_system_password: "R3dh4t123!"
    sap_hana_hsr_hana_primary_hostname: "hana1"
    
    #sample for AWS environment (Change 37fc to fit the lab 
    sap_hana_hsr_full_primary_hostname: "hana1.xxxx.internal"
    sap_hana_hsr_full_secondary_hostname: "hana2.xxxx.internal"


  roles:
    - redhat_sap.sap_hana_hsr
