---
- hosts: hanas

  tasks:
  - name: unregister
    redhat_subscription:
      state: "absent"

  - name: clean
    action: command subscription-manager clean

  - name: re-register
    action: command subscription-manager register --org=7728826 --activationkey=37fc --force


#  vars:
#    sap_rhsm_server_hostname: ''
#    sap_rhsm_org_id: '7728826'
#    rhsm_activationkey: '37fc'

#  roles:
#    - redhat_sap.sap_rhsm
