---
- name: Transfer and execute a script.
  hosts: hanas

  tasks:
  - name: Set node information
    set_fact:
      _nodes: "{{ _nodes | default([]) + [{'hostname': hostvars[item].ansible_hostname, 'address': hostvars[item].ansible_eth0.ipv4.address}] }}"
    run_once: yes
    with_items: "{{ ansible_play_hosts }}"
    when:
      - hostvars[item].ansible_eth0 is defined

  - name: Create additional hosts entries to /tmp/hosts.txt
    lineinfile:
      path: /tmp/hosts.{{ ansible_hostname }}.txt
      line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.{{ ansible_domain }} {{ ansible_nodename }} {{ ansible_hostname }}"
      create: yes

  - name: Copy hosts.txt to local
    fetch:
      src: /tmp/hosts.{{ ansible_hostname }}.txt
      dest: /tmp/hosts.{{ ansible_hostname }}.txt
      flat: yes

  - name: Insert to /etc/hosts on HANA node
    blockinfile:
      path: /etc/hosts
      insertafter: EOF
      marker: "# ANSIBLE Fish-shell basic setup."
      backup: yes
      block: "{{ item }}"
    with_file:
      - /tmp/hosts.hana1.txt
      - /tmp/hosts.hana2.txt

  - name: Transfer the script
    copy: src=/home/ec2-user/hanaworkshop-2021/pkg_fix.sh dest=/home/ec2-user mode=0777

  - name: Execute the script
    command: sh /home/ec2-user/pkg_fix.sh
