---
- name: Transfer and execute a script.
  hosts: hanas

  tasks:
  - name: Set node information
    set_fact:
      _nodes: "{{ _nodes | default([]) + [{'hostname': hostvars[item].ansible_hostname, 'address': hostvars[item].ansible_eth0.ipv4.address}] }}"
    run_once: yes
    with_items: "{{ ansible_play_hosts }}"
    when:
      - hostvars[item].ansible_eth0 is defined

  - name: Distribute hosts file
    become: yes
    template:
      src: hosts.j2
      dest: /tmp/hosts.txt
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Insert to /etc/hosts
    blockinfile: 
      path: /etc/hosts   # 展開対象のファイルパス
      create: yes        # ファイルが存在しない場合は作成(格納フォルダが存在しない場合はフォルダも作成)
      insertafter: EOF   # ファイルの末尾に追加（EOFを文字列にすると、その文字列の直下に追加されます）
      marker: "# {mark} ANSIBLE Fish-shell basic setup." # 追加部分を示すマーカー
      block: "{{item}}"  # 展開する内容（ここではwith_fileで読み込んだファイル内容）
    with_file:
      - /tmp/hosts.txt